config/routes.rb
Rails.application.routes.draw do
  resources :pay_laters
  resources :card_details
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  resources :drivers
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  namespace :api do
    namespace :v1 do
      resources :drivers do
        get :card_details
        post :add_order
        post :add_wallet_history
      end
    end
  end
  # get '/api' => redirect('/swagger/dist/index.html?url=/apidocs/api-docs.json')

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/card_detail.rb
class CardDetail < ApplicationRecord
  belongs_to :driver
  has_many :wallet_histories
  validates :card_no, :expiry_month, :expiry_year, :is_active, presence: true

  scope :default_only, -> { where is_default: true }
end

app/models/driver.rb
class Driver < ApplicationRecord
  belongs_to :user
  has_many :card_details
  has_many :orders
  has_many :wallet_histories
  validates :licence_d, :address, presence: true
  validates_format_of :name, with: /\A[^0-9`!@#$%\^&*+_=]+\z/
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :driver
  has_many :payment_histories, as: :paymentable
  enum payment_type: %i[card_type paylater not_set]
  # enum payment_status: [:published, :unpublished, :not_set]
  validates :amount, :description, :payment_type, presence: true
end

app/models/pay_later.rb
class PayLater < ApplicationRecord
  belongs_to :driver
  has_many :payment_histories, as: :paymentable
end

app/models/payment_history.rb
class PaymentHistory < ApplicationRecord
  belongs_to :paymentable, polymorphic: true
  belongs_to :user
  validates :amount, :payment_type, presence: true
  scope :non_settled_payments, -> { where payment_type: 'paylater', is_settle: false }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :driver
  has_many :payment_histories
end

app/models/wallet.rb
class Wallet < ApplicationRecord
  has_many :wallet_histories
  validates :total_amount, :wallet_type, presence: true
  enum wallet_type: %i[admin user not_set]
end

app/models/wallet_history.rb
class WalletHistory < ApplicationRecord
  belongs_to :card_detail
  belongs_to :driver
  belongs_to :wallet
  validates :total_amount, :payment_histories_ids, presence: true
end

app/controllers/api/v1/drivers_controller.rb
module Api
  module V1
    class DriversController < ApplicationController
      respond_to :json

      swagger_controller :drivers, 'Drivers'

      swagger_api :index do
        summary 'Returns all drivers'
        notes 'Notes...'
      end

      def index
        @drivers = Driver.all
        message = @drivers.present? ? 'Driver List' : 'No drivers present'
        data = {
          data: @drivers,
          message:
        }

        render json: data, status: :ok
      end

      def card_details
        @driver = Driver.find_by(params[:id])
        @card_details = @driver.card_details

        render json: @card_details, status: :ok
      end

      def add_order
        # @driver = Driver.find_by(params[:id])
        @driver = Driver.find_by(id: params[:driver_id])
        @order = @driver.orders.new(amount: params[:amount], description: params[:description],
                                    payment_type: params[:payment_type])
        if @order.save
          @payment = @order.payment_histories.create(amount: @order.amount, payment_on_id: @order.id,
                                                     payment_type: @order.payment_type, paymentable_type: 'Order', paymentable_id: 2, user_id: @driver.user.id)
        end
        @card_details = @driver.card_details

        render json: @order, status: :ok
      end

      def add_wallet_history
        CreateWalletHistory.new(driver_id: params[:driver_id]).create_wallet_history
        data = { message: 'successful' }
        render json: data, status: :ok
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/card_details_controller.rb
class CardDetailsController < InheritedResources::Base
  private

  def card_detail_params
    params.require(:card_detail).permit(:card_no, :expiry_month, :expiry_year, :is_active, :is_default, :driver_id)
  end
end

app/controllers/drivers_controller.rb
class DriversController < InheritedResources::Base
  def index
    debugger
  end

  private

  def driver_params
    params.require(:driver).permit(:name, :address, :licence_d, :date_of_birth, :user_id)
  end
end

app/controllers/pay_laters_controller.rb
class PayLatersController < InheritedResources::Base
  private

  def pay_later_params
    params.require(:pay_later).permit(:total_outstanding, :is_active, :driver_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/card_details_helper.rb
module CardDetailsHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/pay_laters_helper.rb
module PayLatersHelper
end

app/views/card_details/_card_detail.html.erb
<div id="<%= dom_id card_detail %>">
  <p>
    <strong>Card no:</strong>
    <%= card_detail.card_no %>
  </p>

  <p>
    <strong>Expiry month:</strong>
    <%= card_detail.expiry_month %>
  </p>

  <p>
    <strong>Expiry year:</strong>
    <%= card_detail.expiry_year %>
  </p>

  <p>
    <strong>Is active:</strong>
    <%= card_detail.is_active %>
  </p>

  <p>
    <strong>Is default:</strong>
    <%= card_detail.is_default %>
  </p>

  <p>
    <strong>Driver:</strong>
    <%= card_detail.driver_id %>
  </p>

</div>

app/views/card_details/_form.html.erb
<%= form_with(model: card_detail) do |form| %>
  <% if card_detail.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(card_detail.errors.count, "error") %> prohibited this card_detail from being saved:</h2>

      <ul>
        <% card_detail.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :card_no, style: "display: block" %>
    <%= form.text_field :card_no %>
  </div>

  <div>
    <%= form.label :expiry_month, style: "display: block" %>
    <%= form.text_field :expiry_month %>
  </div>

  <div>
    <%= form.label :expiry_year, style: "display: block" %>
    <%= form.number_field :expiry_year %>
  </div>

  <div>
    <%= form.label :is_active, style: "display: block" %>
    <%= form.check_box :is_active %>
  </div>

  <div>
    <%= form.label :is_default, style: "display: block" %>
    <%= form.check_box :is_default %>
  </div>

  <div>
    <%= form.label :driver_id, style: "display: block" %>
    <%= form.text_field :driver_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/card_details/edit.html.erb
<h1>Editing card detail</h1>

<%= render "form", card_detail: @card_detail %>

<br>

<div>
  <%= link_to "Show this card detail", @card_detail %> |
  <%= link_to "Back to card details", card_details_path %>
</div>

app/views/card_details/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Card details</h1>

<div id="card_details">
  <% @card_details.each do |card_detail| %>
    <%= render card_detail %>
    <p>
      <%= link_to "Show this card detail", card_detail %>
    </p>
  <% end %>
</div>

<%= link_to "New card detail", new_card_detail_path %>

app/views/card_details/new.html.erb
<h1>New card detail</h1>

<%= render "form", card_detail: @card_detail %>

<br>

<div>
  <%= link_to "Back to card details", card_details_path %>
</div>

app/views/card_details/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @card_detail %>

<div>
  <%= link_to "Edit this card detail", edit_card_detail_path(@card_detail) %> |
  <%= link_to "Back to card details", card_details_path %>

  <%= button_to "Destroy this card detail", @card_detail, method: :delete %>
</div>

app/views/drivers/_driver.html.erb
<div id="<%= dom_id driver %>">
  <p>
    <strong>Name:</strong>
    <%= driver.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= driver.address %>
  </p>

  <p>
    <strong>Licence d:</strong>
    <%= driver.licence_d %>
  </p>

  <p>
    <strong>Date of birth:</strong>
    <%= driver.date_of_birth %>
  </p>

  <p>
    <strong>User:</strong>
    <%= driver.user_id %>
  </p>

</div>

app/views/drivers/_form.html.erb
<%= form_with(model: driver) do |form| %>
  <% if driver.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(driver.errors.count, "error") %> prohibited this driver from being saved:</h2>

      <ul>
        <% driver.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_area :address %>
  </div>

  <div>
    <%= form.label :licence_d, style: "display: block" %>
    <%= form.text_field :licence_d %>
  </div>

  <div>
    <%= form.label :date_of_birth, style: "display: block" %>
    <%= form.datetime_field :date_of_birth %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/drivers/edit.html.erb
<h1>Editing driver</h1>

<%= render "form", driver: @driver %>

<br>

<div>
  <%= link_to "Show this driver", @driver %> |
  <%= link_to "Back to drivers", drivers_path %>
</div>

app/views/drivers/new.html.erb
<h1>New driver</h1>

<%= render "form", driver: @driver %>

<br>

<div>
  <%= link_to "Back to drivers", drivers_path %>
</div>

app/views/drivers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @driver %>

<div>
  <%= link_to "Edit this driver", edit_driver_path(@driver) %> |
  <%= link_to "Back to drivers", drivers_path %>

  <%= button_to "Destroy this driver", @driver, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoDriver</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pay_laters/_form.html.erb
<%= form_with(model: pay_later) do |form| %>
  <% if pay_later.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pay_later.errors.count, "error") %> prohibited this pay_later from being saved:</h2>

      <ul>
        <% pay_later.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :total_outstanding, style: "display: block" %>
    <%= form.text_field :total_outstanding %>
  </div>

  <div>
    <%= form.label :is_active, style: "display: block" %>
    <%= form.check_box :is_active %>
  </div>

  <div>
    <%= form.label :driver_id, style: "display: block" %>
    <%= form.text_field :driver_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pay_laters/_pay_later.html.erb
<div id="<%= dom_id pay_later %>">
  <p>
    <strong>Total outstanding:</strong>
    <%= pay_later.total_outstanding %>
  </p>

  <p>
    <strong>Is active:</strong>
    <%= pay_later.is_active %>
  </p>

  <p>
    <strong>Driver:</strong>
    <%= pay_later.driver_id %>
  </p>

</div>

app/views/pay_laters/edit.html.erb
<h1>Editing pay later</h1>

<%= render "form", pay_later: @pay_later %>

<br>

<div>
  <%= link_to "Show this pay later", @pay_later %> |
  <%= link_to "Back to pay laters", pay_laters_path %>
</div>

app/views/pay_laters/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pay laters</h1>

<div id="pay_laters">
  <% @pay_laters.each do |pay_later| %>
    <%= render pay_later %>
    <p>
      <%= link_to "Show this pay later", pay_later %>
    </p>
  <% end %>
</div>

<%= link_to "New pay later", new_pay_later_path %>

app/views/pay_laters/new.html.erb
<h1>New pay later</h1>

<%= render "form", pay_later: @pay_later %>

<br>

<div>
  <%= link_to "Back to pay laters", pay_laters_path %>
</div>

app/views/pay_laters/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pay_later %>

<div>
  <%= link_to "Edit this pay later", edit_pay_later_path(@pay_later) %> |
  <%= link_to "Back to pay laters", pay_laters_path %>

  <%= button_to "Destroy this pay later", @pay_later, method: :delete %>
</div>